name: cinedb
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  
  flutter:
    sdk: flutter
  
  dio: ^5.0.0
  get:
  provider: ^6.1.1
  path_provider: ^2.1.1
  cached_network_image: ^3.3.1
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  image_picker: ^1.0.7
  firebase_core: ^2.4.1
  firebase_storage: ^11.0.10

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.0.5

flutter:
  uses-material-design: true

  assets:
    - assets/
