// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC15WC3xH412kl9vG14VYSQkkwX788m6Ho',
    appId: '1:666923496095:web:89dfa37dcd9a589b7aa8aa',
    messagingSenderId: '666923496095',
    projectId: 'cinedb-6e2ce',
    authDomain: 'cinedb-6e2ce.firebaseapp.com',
    storageBucket: 'cinedb-6e2ce.appspot.com',
    measurementId: 'G-XYFLVLEEK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9FMNEr0J0XMX_BTt2nxsmHeCmgppcZlg',
    appId: '1:666923496095:android:aabeb786b236a9a37aa8aa',
    messagingSenderId: '666923496095',
    projectId: 'cinedb-6e2ce',
    storageBucket: 'cinedb-6e2ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi695jzI2bgpPxk9xxo42TRlQibPvWk5s',
    appId: '1:666923496095:ios:c3b46e05de9fb0d77aa8aa',
    messagingSenderId: '666923496095',
    projectId: 'cinedb-6e2ce',
    storageBucket: 'cinedb-6e2ce.appspot.com',
    iosBundleId: 'com.mytech.cinedb',
  );
}
